-- Lock the application tables away from Supabase's Data API.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- WHY THIS EXISTS
--
-- Supabase publishes the `public` schema through PostgREST, reachable with the
-- project's `anon` key. That key is public by design: it ships in browser
-- bundles and mobile apps, and it is printed in the project dashboard.
--
-- Our tables live in `public` and hold password hashes, TOTP secrets, session
-- token hashes, donor names, phone numbers, addresses, PAN, donation records
-- and the audit log. Without the statements below, anyone who knows the project
-- URL can read every one of them with a key they are not supposed to need to
-- protect. No application bug is required; the platform does it by default.
--
-- Two independent controls, because either alone can be undone by accident:
--
--   1. REVOKE — the API roles lose table privileges outright, so a request is
--      refused before row filtering is even reached.
--   2. ROW LEVEL SECURITY with NO POLICIES — every row is invisible to any role
--      that RLS applies to. Should a future `GRANT` restore privileges (the
--      Supabase dashboard does this when you use its table editor), this still
--      holds the line.
--
-- The application is unaffected. It connects as the table OWNER, and an owner
-- bypasses RLS unless FORCE ROW LEVEL SECURITY is set — which it deliberately
-- is not. Migrations, the seed, the API and the worker all keep full access.
--
-- This is NOT the Supabase-native pattern of writing per-row policies for
-- `auth.uid()`. We do not use Supabase Auth: authorization is decided by the
-- API's permission guards (decision A9), which is the only place it can account
-- for re-authentication, audience separation and separation of duties. Exposing
-- a second, parallel authorization surface with different rules would mean two
-- answers to the same question.
--
-- Also turn OFF the Data API in the dashboard (Settings → API → Exposed
-- schemas). This migration is the belt; that setting is the braces.
-- ─────────────────────────────────────────────────────────────────────────────

DO $$
DECLARE
  target text;
  api_roles text[] := ARRAY['anon', 'authenticated'];
  existing_roles text[];
BEGIN
  -- The `anon` and `authenticated` roles exist only on Supabase. Local Postgres
  -- and the CI container have neither, so every statement here is conditional:
  -- the migration must apply cleanly everywhere, not only where it matters.
  SELECT array_agg(rolname::text)
    INTO existing_roles
    FROM pg_roles
   WHERE rolname = ANY (api_roles);

  IF existing_roles IS NOT NULL THEN
    FOREACH target IN ARRAY existing_roles LOOP
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', target);
      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', target);
      EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM %I', target);
      EXECUTE format('REVOKE USAGE ON SCHEMA public FROM %I', target);

      -- Supabase sets default privileges that re-grant access to every table
      -- created later. Without this, the next migration quietly reopens the hole.
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I', target
      );
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I', target
      );
    END LOOP;

    RAISE NOTICE 'Data API roles revoked from public schema: %', existing_roles;
  ELSE
    RAISE NOTICE 'No Supabase API roles present — REVOKE steps skipped (this is expected off Supabase).';
  END IF;
END
$$;

-- Row level security on every application table, with no policies at all.
--
-- Deliberately generated by looping over the catalogue rather than listing the
-- 28 tables by name: a hand-written list is a list someone forgets to extend.
-- `apps/api/test/database.spec.ts` asserts that EVERY table has RLS enabled, so
-- a table added by a later migration without it fails CI rather than shipping.
DO $$
DECLARE
  target record;
BEGIN
  FOR target IN
    SELECT c.relname
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public'
       AND c.relkind = 'r'
       AND c.relname <> '__drizzle_migrations'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', target.relname);
  END LOOP;
END
$$;
